### ISSUE TITLE
Bit Flag Used

### ISSUE THREAD

**Issue by TekkaGB** [AnimatedSwine37/Hyperspeed-Reading-Plus#1]
I noticed you used flag 123456789.  While it gets set on/off in the session, I think it doesn't get saved in the file.  I think the max flag thats gets saved to the file in its proper block is 6656, so you may want to find a lesser value that's unused.  I may be wrong but that's what I've been told.

**Comment by AnimatedSwine37** [comment]
Thanks for the heads up but the flag is used as a kind of temporary way to communicate between the two flowscripts as to whether the bookshelf menu needs to be opened again so it doesn't really matter that it isn't saved in the file.
